/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.livraria.view;

import br.com.livraria.connectionFactory.ConnectionFactory;
import br.com.livraria.dao.GeneroDao;
import br.com.livraria.model.Genero;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class TelaGenero extends javax.swing.JInternalFrame {

    private GeneroDao generoDao;
    private EntityManager em;
    
    public TelaGenero() {
        initComponents();
        prencherTabela();
    }
    
    private void iniciaGeneroDao(){
         em = new ConnectionFactory().getEntityManager();
        
         generoDao = new GeneroDao(em);
    }
    private void limpaCampo(){
        txtNome.setText("");
    }
    
    private void prencherTabela(){
        iniciaGeneroDao();
        
        ArrayList<Genero> generos = (ArrayList<Genero>) generoDao.listarGeneros();
        
        DefaultTableModel modelo = (DefaultTableModel) tblGenero.getModel();
        
        modelo.setNumRows(0);
        
        for(Genero genero: generos){
            modelo.addRow(new Object[]{genero.getId(),genero.getNome()});
        }
        em.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGenero = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        tblGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGeneroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGenero);
        if (tblGenero.getColumnModel().getColumnCount() > 0) {
            tblGenero.getColumnModel().getColumn(0).setMinWidth(120);
            tblGenero.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblGenero.getColumnModel().getColumn(0).setMaxWidth(120);
        }

        jLabel1.setText("Nome");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
         iniciaGeneroDao();
         
         Genero genero = new Genero(txtNome.getText());
         
         generoDao.adicionarGenero(genero);
         
         JOptionPane.showMessageDialog(null, "Genero Adicionado com sucesso");
         
         prencherTabela();
         em.close();
         limpaCampo();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tblGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGeneroMouseClicked
        if(tblGenero.getSelectedRow() != -1){
            String nome = (String) tblGenero.getValueAt(tblGenero.getSelectedRow(), 1);
            
            txtNome.setText(nome);
        }
    }//GEN-LAST:event_tblGeneroMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(tblGenero.getSelectedRow() != -1){
            
            int id = (int) tblGenero.getValueAt(tblGenero.getSelectedRow(), 0);
            
            iniciaGeneroDao();
            
            generoDao.excluirGenero(id);
            em.close();
            limpaCampo();
            prencherTabela();
            
            JOptionPane.showMessageDialog(null, "Genero excluido com sucesso");
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if(tblGenero.getSelectedRow() != -1){
            
            iniciaGeneroDao();
            
            int id = Integer.parseInt(tblGenero.getValueAt(tblGenero.getSelectedRow(), 0).toString());
            
            String nome = txtNome.getText();
            
            iniciaGeneroDao();
            
            generoDao.editarGenero(id, nome);
            
            limpaCampo();
            prencherTabela();
            em.close();
            
            JOptionPane.showMessageDialog(null, "Genero editado com sucesso");
            
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGenero;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
